version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "serverless-webinar-step-functions-1"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1p0o6wyncmu4r"
s3_prefix = "serverless-webinar-step-functions-1"
region = "eu-west-1"
capabilities = "CAPABILITY_IAM"
